import './global.css';
import { Prompt } from 'next/font/google';

import { AuthProvider } from '../client/auth-provider';

export const metadata = {
  title: 'Welcome to diet-app',
  description: 'Generated by create-nx-workspace',
};

const prompt = Prompt({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={prompt.className}>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
