import './global.css';

import { AppAuthProvider } from '../client/app-auth-provider';

export const metadata = {
  title: 'Welcome to diet-app',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AppAuthProvider>{children}</AppAuthProvider>
      </body>
    </html>
  );
}
